name: Dev Branch

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy Application
      shell: cmd
      run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:contentPath="D:\a\flask_app\flask_app" -dest:contentPath="C:/inetpub/wwwroot",computerName="http://18.191.87.149/msdeploy.axd?",username="Administrator",password="&=d3JDXw%kDDeeEd8gptEsICqWelWAu7",authtype="NTLM"'
