- name: Deploy Application
shell: cmd
run: '"C:/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe" 
-verb:sync -allowUntrusted -source:contentPath="Publish/CICDPractice/" 
-dest:contentPath="${{ env.WEBSITE_CONTENT_PATH }}",
computerName="${{ env.IIS_SERVER_COMPUTER_NAME }}/msdeploy.axd?site=${{ env.IIS_WEBSITE_NAME }}",
username="${{ env.IIS_SERVER_USERNAME }}",
password="${{ env.IIS_SERVER_PASSWORD }}",
authtype="Basic"'
         
