name: Dev Branch

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy Application
      shell: cmd
      run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -useCheckSum -source:contentPath="D:\a\flask_app\flask_app" -dest:contentPath="C:\inetpub\wwwroot\flaskproject",computerName="https://ec2-18-216-110-79.us-east-2.compute.amazonaws.com:8172/msdeploy.axd",username="EC2AMAZ-MABDNJ9/Administrator",password="q368QT&HQT(Te!tfEPUVxDz9(j&Go$Gx",authtype="Basic"'
      
